### ISSUE TITLE
Logging into Markdown Editor displays error message "Unable to determine DSN for this user and this context"

### ISSUE THREAD

**Issue by ysam21** [verida/markdown-notes-demo#107] opened 2022-04-01 05:07 UTC
Logging into Markdown Editor displays error message "Unable to determine DSN for this user and this context". Can use Markdown Editor as normal once error message times out.

Steps to replicate
- Go to https://markdown-editor.demos.testnet.verida.io/
- Log out
- Log back in
- See error message displayed in the top right hand corner
 ![image](https://user-images.githubusercontent.com/92969583/161198386-58d08a10-0a22-4809-a75d-3d4021398924.png)
- Once the message times out it disappears

Vault Version: 0.2.8 Internal (iOS)

**Comment by nick-verida** [comment] 2022-04-01 05:19
I was able to confirm this on version 0.2.8 Internal too. 

My DID is did:vda:0x0e0d2a78b8e7b6e66d9e2c50bc72ef0871c66291

**Comment by nick-verida** [comment] 2022-04-01 05:27
Before logging into Markdown Editor the services in the DID doc looks like this:

```
   "service": [
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#database",
        "type": "VeridaDatabase",
        "serviceEndpoint": "https://db.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#messaging",
        "type": "VeridaMessage",
        "serviceEndpoint": "https://messages.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#notification",
        "type": "VeridaNotification",
        "serviceEndpoint": "https://notifications.testnet.verida.tech/"
      }
    ],
```

**Comment by cmcWebCode40** [comment] 2022-04-01 05:32
I tried logging in with my old account but didn't get the above error. 
seems this issue is related to a new account?  

vault version v0.2.8(1)

**Comment by nick-verida** [comment] 2022-04-01 05:33
After logging in my DID document looks like this:

```
    "service": [
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#database",
        "type": "VeridaDatabase",
        "serviceEndpoint": "https://db.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#messaging",
        "type": "VeridaMessage",
        "serviceEndpoint": "https://messages.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x34203e78c3109232f2c25981939387ed76205501dfe07047205c4b076b49eed1#notification",
        "type": "VeridaNotification",
        "serviceEndpoint": "https://notifications.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x4f159fff0bef2547e510be4bf447da2b08b02f9dba3402e5e3759492fc290c1c#database",
        "type": "VeridaDatabase",
        "serviceEndpoint": "https://db.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x4f159fff0bef2547e510be4bf447da2b08b02f9dba3402e5e3759492fc290c1c#messaging",
        "type": "VeridaMessage",
        "serviceEndpoint": "https://messages.testnet.verida.tech/"
      },
      {
        "id": "did:vda:0x7e8044191c0625280ea419f72cecbae3c5e5dbc6?context=0x4f159fff0bef2547e510be4bf447da2b08b02f9dba3402e5e3759492fc290c1c#notification",
        "type": "VeridaNotification",
        "serviceEndpoint": "https://notifications.testnet.verida.tech/"
      }
    ],
```

So this all looks good.

**Comment by nick-verida** [comment] 2022-04-01 05:39
The second time you login with the same DID it works fine.

**Comment by nick-verida** [comment] 2022-04-01 05:59
It's possible this is due to the version of the Verida libraries. I'll test that before pushing this to verida-js or vault.

**Comment by nick-verida** [comment] 2022-04-01 06:38
On the latest version of the Verida libraries we still get the same error
```
    "@verida/account-web-vault": "^1.1.10",
    "@verida/client-ts": "^1.1.13",
```

**Comment by tahpot** [comment] 2022-04-03 23:36
I am running the latest version of markdown editor on localhost using `Verida Vault Internal 0.2.8 (1)`.

I can confirm this is broken on the first SSO login, but works on subsequent.

This indicates it's a new bug in the Verida Vault.

I will now test using the web sandbox as I can easily login to different application contexts and output the SSO response from the Vault.

---

Here's a breakdown of the testing I completed:

I successfully logged in using:

- A very old account
- An old account of Nick's (did:vda:0x97e3574571Cf38cbd62f39dc581fB01E0Cdf2E20)

I failed to login with:

- A brand new account (did:vda:0x12a38353433d7d7405062db439fbdc3cd3bc7c09)
- `Sandbox_test` - A recently created account when we were having DID issues (did:vda:0x2A82C4B8c57F7A1800e7F948e8F92De4926517dd)
- `SB test 2` - Another recently created account when we were having DID issues (did:vda:0x404B091c691305C68Cfc8179020dFdd7F46DF7b7)

**Comment by nick-verida** [comment] 2022-04-03 23:38
> This indicates it's a new bug in the Verida Vault

There are reports of this in the previous version of the Vault. They are mixed through the reports of the Vault incorrectly setting the endpoints AND issues related to https://github.com/verida/verida-js/issues/180 though, so the reporting is confused.

**Comment by tahpot** [comment] 2022-04-03 23:50
I have tested using web sandbox and found the SSO is working fine when signing into a context for the first and subsequent times, using a new DID.

I observed the data returned by the Vault and it appears to be as expected.

As such, I believe the Markdown editor needs to be investigated further with information about why it displays that error message. What line number is that coming from? What is the data that is causing that message to be shown?

Handing this issue over to @cmcWebCode40  to investigate further to obtain that info.

**Comment by cmcWebCode40** [comment] 2022-04-07 02:46
Sorry, @taphot, 

i missed this comment i will , investigate the markdown editor again to find out the issue.

**Comment by cmcWebCode40** [comment] 2022-04-11 19:25
@tahpot, 

I'm still investigating this issue, have found out exactly where is error is coming from in my code, 

inorder for me to reproduce the error I will always have to create a new account after first-time login, the error does not re-occur. 


but I could  see a clue from my console log here 

<img width="1000" alt="Screenshot 2022-04-11 at 20 22 01" src="https://user-images.githubusercontent.com/54280620/162814456-b0babb87-b6b0-40ff-bb73-53d0a3e66ea3.png">


<img width="1000" alt="Screenshot 2022-04-11 at 20 22 26" src="https://user-images.githubusercontent.com/54280620/162814642-8410ad65-82f0-42d3-a97e-efa7fce23638.png">



still giving me hard times but I'm still suspecting the markdown demo.

**Comment by cmcWebCode40** [comment] 2022-04-21 06:27
Other investigations from the network requests that returned error response

1. a request was made to this URL `https://db-sg1.testnet.verida.tech/user/get?did=did:vda:0x476Fa00518971FCC0b7B342F4b43e5f9892Cbbf8` which return a response 

```
{"status":"fail","data":{"did":"Invalid DID specified"}}
```

2. Another request was made to this endpoint `https://db-sg1.testnet.verida.tech/user/create`  twice which gave a response 

first response
```
{"status":"success","user":{"username":"v9761be71fc48d5134743faebfac2a922e706dd90152857cec51edaeb718654a8","dsn":"https://v9761be71fc48d5134743faebfac2a922e706dd90152857cec51edaeb718654a8:f7883ae5d3b394e66202fd131c4cbc88013188031bb53c2ddd47282d96521fda@dbc1.sg.testnet.verida.tech:5984","salt":"db6f0c2355ff9abed8665470e7d172f6"}}
```

second response
```
{"status":"fail","code":100,"data":{"did":"User already exists"}}

```

FYI: this request( `https://db-sg1.testnet.verida.tech/user/create`) is been made happens for a new account first-time login.

**Comment by nick-verida** [comment] 2022-05-01 23:53
@cmcWebCode40 we need to know why this is happening here and not on other apps.

**Comment by nick-verida** [comment] 2022-05-04 05:51
Fixed, merged and deployed

**Closed by nick-verida** 2022-05-04 05:51 UTC
Labels: bug
